### ISSUE TITLE
Adding Scoring system/Reporting system for Scanners

### ISSUE THREAD

**Issue by preetkaran20** [SasanLabs/VulnerableApp#130]
**Is your feature request related to a problem? Please describe.**
As Scoring is one of the major task which is needed by the Vulnerable App for rating various scanners so we need a way to add/report the scores of Scanners.

**Describe the solution you'd like**
Say this tool is going well and now scanner like to rate themselves on how much percentage of vulnerabilities are covered by them then we need to give some kind of report.
Reporting is one of the task which can help this tool to work as a compliance matrix so we need to add such utility and i am thinking to add something very engineerish way not just count.

**Describe alternatives you've considered**
Nothing is the alternative

**Additional context**
thanks to @psiinon Project leader of @zaproxy for giving such valuable suggestion.

**Comment by preetkaran20** [comment]
My perspective on this:
so as we have list of endpoints which are vulnerable, we know the attack vectors for the vulnerability and we also know the Vulnerability type so now lets support @zaproxy gave us a list of endpoints which it thinks that they are vulnerable and what is the vulnerability type in them and now i can tell the percentage of covered vulnerabilities and what ever is not covered, i can give some kind of report which can tell the Vulnerable payloads, Vulnerability types etc.

**Comment by preetkaran20** [comment]
1st commit related to Reporting System: https://github.com/SasanLabs/VulnerableApp/pull/145
Will update this PR with more information.

**Comment by psiinon** [comment]
I wouldnt try to analyse reports from scanners - that could be too much work for you. If you just provide a simple way of describing the vulnerabilities then scanner authors can consume that - less work for you and mapping your results to each scanner will be the responsibility of the scanner authors.
Kind of info that you could provide:
```
 url : https://www.example.com/xss1
 type : XSS-reflected
 method : GET
 parameter : search
 example-payload : "/><script>alert(1);</>
```

**Comment by preetkaran20** [comment]
@psiinon  I didn't got your point completely. 
As currently vulnerableApp provides this information that what is the vulnerability type, what is the URL etc. Now say i am a scanner author, how should i use it?  can you please elaborate more on the usecase.

**Comment by psiinon** [comment]
I want to configure ZAP to automatically run against apps like VulnerableApp.
For that I'll need to:

1. Start ZAP and the target app
1. Spider then active scan the app
1. Score - work out which of the ZAP alerts are right, and work out the FPs and FNs
1. Stop ZAP and the target app
1. Report any changes in the results

Scoring is the hard part.
Heres my script for scoring vs wavsep https://github.com/zapbot/zap-mgmt-scripts/blob/master/wavsep/wavsep-score.py - its painful!

What I'd like is a simple structured doc/url which tells me which vulns are there. I can then match that to ZAP alerts - I'm happy to maintain that as well :) 
I want to know how many FPs and FNs we have and what they are. I'll then want to know when these chance, eg if ZAP gets worse or better.

Does that make sense?

**Comment by preetkaran20** [comment]
Hi @psiinon ,

Thanks for wonderful explanation, I got the way you are looking at this. Currently VulnerableApp gives the information about the 
1. Vulnerable Endpoint
2. Vulnerability Type
3. Input Parameter related information (Is somewhat not written with machine readable format, it is made human understandable but can be done easily).

However the part of telling the Scanner that it has succeeded in finding vulnerability is little tricky and it is not there so at a minimum level as you suggested we can match the vulnerability type matches between two tools that is ZAP and Vulnerable app we can roughly say that Scanner has found the vulnerability. 

I think this makes sense. Will work from this perspective.

thanks,
Karan

**Comment by preetkaran20** [comment]
This has one important step as https://github.com/SasanLabs/VulnerableApp/issues/147

**Comment by preetkaran20** [comment]
Framework changes for adding ParameterName, SampleValues and Request Location :
https://github.com/SasanLabs/VulnerableApp/pull/153

**Comment by preetkaran20** [comment]
Hi @psiinon ,

Following will be the sample response from the VulnerableApp:
 ```
[ {
    "url": "http://192.168.0.148:9090/vulnerable/JWTVulnerability/LEVEL_1",
    "location": "QUERY_PARAM",
    "parameter": "JWTToken",
    "sampleValues": [
      "ey.."
    ],
    "method": "GET",
    "vulnerabilityTypes": [
      "JWT"
    ]
  } ]
```

Here `Sample Values` will be useful for the scanners which depend on the original request input like JWT Scanner which takes the JWT token from the Cookie or Header etc and then change that value (Something which we refer as original message in ZAP).

Along with this i have also exposed a new endpoint which returns the `SiteMap` which can be useful for Spiders and then active scanners so ZAP can use it to directly too, however that alone cannot be sufficient in case Scanner depend on Original Message like JWT scanner. 

PR containing these changes: https://github.com/SasanLabs/VulnerableApp/pull/153/ 

please share your thoughts.

thanks,
Karan

**Comment by preetkaran20** [comment]
Added more changes related to it https://github.com/SasanLabs/VulnerableApp/pull/154

**Comment by preetkaran20** [comment]
https://github.com/SasanLabs/VulnerableApp#how-can-vulnerability-scanning-tools-use-vulnerableapp-

**Comment by psiinon** [comment]
That looks great! You might want to replace the IP addr with a token or standard value as that will be different a lot of the time, but other than that it looks great! Will you have a documented set of locations and vulnerability types? Once this is in place I'll do my best to implement a ZAP mapping :) That could be included in this repo or one of ours, I dont mind which. It would make teating ZAP vs this app so much easier!

**Comment by preetkaran20** [comment]
Hi @psiinon,

All these URL are dynamically generated hence IP addr will be of the machine in which this app is running and i think then it will not be an issue. we can change into some token but then at ZAP end we need to correct it. Please suggest 
Classes containing the List of Locations and vulnerability types: 
Locations: https://github.com/SasanLabs/VulnerableApp/blob/master/src/main/java/org/sasanlabs/internal/utility/annotations/RequestParameterLocation.java
Vulnerability Types:
https://github.com/SasanLabs/VulnerableApp/blob/master/src/main/java/org/sasanlabs/vulnerability/types/VulnerabilitySubType.java

thanks,
Karan

**Comment by psiinon** [comment]
Ah! - if its dynamically generated then thats even better :)
Those definitions look fine - you might want to include an endpoint which returns them?

**Comment by preetkaran20** [comment]
hmm ... sure, Need to evaluate whether to include in the same scanner endpoint or different endpoints. Both have pros and cons, where scanner endpoint can be one stop solution but might make the response cluttered. What is your take on this.

**Comment by preetkaran20** [comment]
Hi @psiinon,

I have introduced a new endpoint called '/scanner/metadata' which will provide the information about vulnerability types and locations.

e.g.
```
{
  "availableVulnerabilities": [
    "BLIND_SQL_INJECTION",
    "ERROR_BASED_SQL_INJECTION",
    "UNION_BASED_SQL_INJECTION",
    "REFLECTED_XSS",
    "PERSISTENT_XSS",
    "DOM_BASED_XSS",
    "CLIENT_SIDE_VULNERABLE_JWT",
    "SERVER_SIDE_VULNERABLE_JWT",
    "INSECURE_CONFIGURATION_JWT",
    "NULL_BYTE"
  ],
  "availableLocations": [
    "BODY",
    "HEADER",
    "COOKIE",
    "QUERY_PARAM",
    "PATH_PARAM"
  ]
}
```
PR: https://github.com/SasanLabs/VulnerableApp/pull/157
Currently i am assuming that the names of the vulnerabilities are self explanatory and mostly standard names so didn't added the bean with description. Will do that if required in future.

**Comment by psiinon** [comment]
This is looking awesome! 
Out of interest have you run ZAP against it? We're aiming to do that asap in any case, but just wondered if you already have some results you could share...

**Comment by preetkaran20** [comment]
Hi @psiinon ,

I had ran ZAP against vulnerableapp  and using sitemap.xml ZAP was able to find many vulnerabilities however as this new endpoint "/scanner" is not being used by ZAP as we have not written code to understand it hence some vulnerabilities it is not able to find.

thanks,
Karan

**Comment by preetkaran20** [comment]
Hi @psiinon,

I was thinking how in ZAP side we can use the VulnerableApp, so i was thinking a Simple Python/JS script can be written which reads the /scanner api response (https://github.com/SasanLabs/VulnerableApp/issues/130#issuecomment-662089906) and then the script fires some requests and then it starts Active Scanner which finds the vulnerabilities and then then this script will evaluate it. 

Is my understanding correct ? or are you looking at some other way ? 

thanks,
Karan

**Comment by psiinon** [comment]
Hiya @preetkaran20 

We used to scan both wivet and wavsep automatically. The results are all public on http://zapbot.github.io/zap-mgmt-scripts/scans.html
They were running on Mozilla AWS VMs and broke sometime ago. However we are in the process of fixing them - I uploaded the latest wavsep scan manually.
For wavsep I am creating a github workflow which:

1. Starts wavsep in a docker container
1. Starts ZAP in a docker container
1. Runs ZAP against wavsep using the ZAP API, probably in another docker container
1. Scores the result (using a pretty nasty script;) and pushed the results to the github webpages site

We want to do something similar with other apps like VulnerableApp.
When we run ZAP we use the std spider and the active scanner. We can also use the ajax spider if necessary.
We want to test all pages with all rules so that we can detect false positives - if an SQLi rule incorrectly reports a problem on a page with only an XSS vuln then we want to fix it :)
Does that make sense?

I'm working on the wavsep one right now as this used to work and has lots of tests. However I can look at the VulnerableApp testing soon after that - your scoring system will make it so much easier :D

**Comment by preetkaran20** [comment]
Hi @psiinon ,

Yes this makes sense, i am ok with infra however i think only spidering and running active scanner might not give all the results reason being say an Api expects JWT token as input  and hence spidering and active scanner doesn't know about it so the original message might not have that JWT token and hence cannot result in finding issues. Can we though as application expects `say a particular parameter as input`

For SQLi and XSS standard payloads are there hence it works and i think 85% of the use cases it will work. Hence i thought the sample values or parameter names can help ZAP to fire the requests using proper input payloads (by writing utility as a community script to know the correct inputs, parameter names etc) and then active scanner will work as is.

Like -> Run Spider, run a utility script (which fires the request using sample values of /scanner and parameter names), Run Active Scanner

What is your take on this.

thanks,
Karan

**Comment by preetkaran20** [comment]
Closing this and tracking Integration with ZAP in another Enhancement.

thanks,
Karan
