### ISSUE TITLE
Adding Integration with Karate or any other API Integration tool

### ISSUE THREAD

**Issue by preetkaran20** [SasanLabs/VulnerableApp#179]
**Is your feature request related to a problem? Please describe.**
When ever we do framework changes it becomes very tough to know if something is not working. It would be great if we can add the API Integration tool like Karate or any other way to reduce the regression testing effort.

**Describe the solution you'd like**
Add Karate and run it as a GitHub actions so that with Every PR it will run and report issues on Framework. It is also possible to write unit tests. So this task is to evaluate and pick one or both tasks and fix this manual effort.

**Comment by soil-droid** [comment]
can i work on this?

**Comment by preetkaran20** [comment]
Hi @soil-droid ,

Sure. Assigning this to you.

thanks,
Karan

**Comment by preetkaran20** [comment]
Hi @soil-droid ,

are you looking into this? or can i unassign this issue?

thanks,
Karan

**Comment by preetkaran20** [comment]
Closing this as created: https://github.com/SasanLabs/VulnerableApp/issues/319
