### ISSUE TITLE
[Don't Pick] Adding Swagger/OpenApi for all the Api's

### ISSUE THREAD

**Issue by preetkaran20** [SasanLabs/VulnerableApp#184]
**Is your feature request related to a problem? Please describe.**
I was under impression that Owasp doesn't understand OpenApi and may be it requires a Api definition but after reading https://www.zaproxy.org/blog/2017-06-19-scanning-apis-with-zap/ article by @psiinon i think ZAP understands it so scanner endpoint can be moved to OpenApi and make our custom annotations light weight.

**Describe the solution you'd like**
Adding OpenApi's annotations over the Api endpoints.

**Describe alternatives you've considered**
This is for now not required for now but better to think on this.

**Additional context**
We require annotations for the information which is useful for generating __vuln.yml but might not require for api definition.

**Comment by AlessandroArosio** [comment]
I'll take this on :)

**Comment by preetkaran20** [comment]
Hi @AlessandroArosio ,

We are not very clear on this requirement as this was created with something different in mind and this might seems invalid for now as vuln.yml is now out of scope. 
Sorry for inconvinence.

thanks,
Karan
