### ISSUE TITLE
User Interface Improvements [Analysis]

### ISSUE THREAD

**Issue by preetkaran20** [SasanLabs/VulnerableApp#185]
**Is your feature request related to a problem? Please describe.**
VulnerableApp's UserInterface is having some alignment issues and also cannot scale as we increase the vulnerability types.
Some idea's are like adding Left Nav bars for Vulnerability types and another for Levels.

This task is to collect the feedbacks, issues in UI and other design consideration

**_Feedbacks are welcome_**

**Comment by hemantgs** [comment]
Might I suggest

- Introducing a Table view ,with filters that shows vulnerabilities and clicking on them shows the levels

- Decouple UI from the backend maybe ? Use yarn or tools like that to serve static content

**Comment by preetkaran20** [comment]
can you please add some sample screen explaining your suggestion.

hmm actually i had added static content in application with the reason that the contributors need not to setup 2 things to make it work. i.e. Yarn and backend and that might make difficult for them. 
However yes we should move to yarn etc and actually each tech has some or the other vulnerabilities so we need to think of onboarding them to the platform and also make project light at the same time.

**Comment by preetkaran20** [comment]
https://github.com/SasanLabs/VulnerableApp/issues/190

**Comment by hemantgs** [comment]
> can you please add some sample screen explaining your suggestion.
![image.png](https://user-images.githubusercontent.com/13389954/91022115-56e6fd80-e612-11ea-8b70-9a24c90bf76b.png)
I was thinking something like this maybe

And I see, that makes sense to keep a simple ux overall

**Comment by preetkaran20** [comment]
HI @hemantgs ,

I was thinking something like 
![image](https://user-images.githubusercontent.com/13570884/91091719-a3fbbb80-e674-11ea-9cf2-849c5ce54b79.png)
where we have master-detail structure. Master being Vulnerability, 2nd master is level and detail is the actual vulnerability.

Currently it is similar however master is not scrollable, neither 2nd master. WDTY ?

thanks,
Karan

**Comment by hemantgs** [comment]
This looks good too .. Can think about enriching it bit more , should be good for starters

**Comment by preetkaran20** [comment]
we can think more on this and look at other applications too.

**Comment by preetkaran20** [comment]
Alignment issues can be tackled with issue: https://github.com/SasanLabs/VulnerableApp/issues/213 but as our UI has left nav bar and with the addition of more vulnerabilities scrolling can be little tricky so this issue is to design some scalable User interface.
After this is done an implementation issue https://github.com/SasanLabs/VulnerableApp/issues/186 can be picked up.

thanks,
Karan

**Comment by preetkaran20** [comment]
use Figma for XD then we can build the UI from that.

**Comment by preetkaran20** [comment]
Done with https://github.com/SasanLabs/VulnerableApp-facade
