### ISSUE TITLE
Removing Pom.xml

### ISSUE THREAD

**Issue by preetkaran20** [SasanLabs/VulnerableApp#189]
**Is your feature request related to a problem? Please describe.**
As we need to maintain both pom.xml and build.gradle hence it is tough. so we are thinking that we can remove pom.xml.
With the removal of pom.xml we also need to take care of any documentation reference and also need to add that to release notes or any other places it is referenced.

**Comment by pavluchenko** [comment]
Hi, please assign this issue to me. I would like to work on this

**Comment by preetkaran20** [comment]
@pavluchenko has done this change and it is merged. so closing this issue.

thanks,
Karan
