### ISSUE TITLE
Language agnostic vulnerability addition

### ISSUE THREAD

**Issue by hemantgs** [SasanLabs/VulnerableApp#199]
**Is your feature request related to a problem? Please describe.**
Someone wanting to introduce a new vulnerability have to open up the code and add the desired vulnerability add the annotations then run it, someone unfamiliar with Java might find that difficult

**Describe the solution you'd like**
A way to `register` a certain vulnerability , it could be via an API , a `/POST` or a `/PUT `with file upload.
Could probably think about just allowing certain type of vulnerabilities to be added this way as a start.

We could also provide an export option if we allow users to make additions so they can simply kill the server and load it again with the same changes

**Comment by preetkaran20** [comment]
@hemantgs great idea. Need to evaluate it. 
Similar idea's : 
1. https://github.com/SasanLabs/VulnerableApp/issues/119
2. https://github.com/SasanLabs/VulnerableApp/issues/106
3. https://github.com/SasanLabs/VulnerableApp/issues/176

**Comment by preetkaran20** [comment]
Notes:
I think ZAP is written in java but uses Jython (For Python) and Nashorn (GraalVM) (For Javascript) for executing both the languages under same platform. we can utilize those too.

**Comment by hemantgs** [comment]
So I was thinking a little bit on this , to start with we can provide better extensibility for java by supporting loading vulnerabilities from an external jar .. 
So say a user starts our docker container with a `--external` flag pointing to location of a jar that has custom vulnerabilities that follow a a template that we define possibly with an annotation .. 
The app should expose whatever is contained in the jar as well , the jar can have 1or more vulnerable classes.
We could follow a similar approach for support for other languages too via possibly Graal.
Let me know what you think @preetkaran20

**Comment by preetkaran20** [comment]
hmm. Yes this can be one way but might not work if someone want to do the same using our binary. I was thinking from the perspective of Market place where some can go and host the vulnerability classes and from tool they can download those classes.
The same approach as what you are telling, if we do using market place would be great.  What do you think ?

**Comment by hemantgs** [comment]
By market place do you mean to have a common app hosted somewhere from where people can add their classes  and others can download from and use them ?

**Comment by preetkaran20** [comment]
Yes, correct i am thinking about it.

**Comment by hemantgs** [comment]
Hmmm , in that case my suggestion would be to start with an API design , the UI can come later , maybe start with wireframes first ..
Marketplace should live in a different repo ? I am not sure .. what do you think

**Comment by preetkaran20** [comment]
hmm, actually yes. 

UI is already derived by the annotations so we need to get the similar information from the marketplace. we already have endpoint called `allEndPointJson` and `allEndPoint` and if the information from the marketplace jar is same we can build the UI.

I think our backend framework is quite extensible and it doesn't require any change for achieving this functionality. Only the UI is something which is a challenge.

**Comment by preetkaran20** [comment]
For more information please look at : https://github.com/SasanLabs/VulnerableApp/blob/master/src/main/java/org/sasanlabs/controller/VulnerableAppRestController.java#L64

**Comment by hemantgs** [comment]
I see , in that case the marketplace will not be public right ? Meaning it will be tied to the lifecycle of VulnerableApp

**Comment by preetkaran20** [comment]
may be or may not be ... this depends on how we approach it.
If for example say there are vulnerable applications which are hosted in cloud then once a user comes to our vulnerable Application and inserts the URL of that applications (a similar endpoint as allEndPointJson) then we can utilise that information and run the entire application from our application.

If we go by downloading Jar and then use it as embedded jar in VulnerableApp then yes lifecycle will be tied up. we can be flexible and go with both of them. What is your perspective  on this.

**Comment by hemantgs** [comment]
Hmm that makes sense , need a clear plan on how to take it forward though

**Comment by preetkaran20** [comment]
Hi @hemantgs , 

I think we need to note down approaches and there pros/cons and also discuss among our selves some of the questions like:

1.  is there anyone interested in something like market place, 
2. Anyone interested in already written application to be integrated with VulnerableApp
3. How to proceed from now onwards as we have many vulnerabilities covered but still some are left so shall we pick this or 
are there other things left which we need to focus on. Mainly what is the current state of this project and what are the future goals and does this issue comes before them in priority or aligns with the goals?

How about discussing these in next meeting ? May be this monday ?(i am ok with weekend too). Please let me know if you are free.

thanks,
Karan

**Comment by preetkaran20** [comment]
https://github.com/SasanLabs/VulnerableApp-nginx some other way to achieve the same.

**Comment by preetkaran20** [comment]
Hi @hemantgs ,

As part of a new initiative https://github.com/SasanLabs/VulnerableApp-facade we have introduced a new mechanism where docker is added such that the developers can add the vulnerabilities in their choice of tech stack. please have a look and let me know if it serves the purpose.

thanks,
Karan
