### ISSUE TITLE
Pressing back button from one of the pages in the UI exits the page instead of going one page back

### ISSUE THREAD

**Issue by hemantgs** [SasanLabs/VulnerableApp#200]
**Describe the bug**
back button exits the page in the UI

**To Reproduce**

1. Open UI
2. Click Learn Security
3. Click Back button in browser
4. Browser exits the webpage and goes to the website that was open before this

**Expected behavior**
Back button should go back to the home page of VulnerableApp

**Comment by preetkaran20** [comment]
For background of the issues:
UI is designed in a way that it comprise of bunch of Div's and once a button is clicked one div is marked as hidden (using Css) and others divs are visible.

to solve this issue i think we need to change the histories of the window such that when backbutton is clicked the history is popped out to addess this issue.

thanks,
Karan

**Comment by ShareACoke1** [comment]
Hi there! I would like to work in this.

**Comment by preetkaran20** [comment]
Assigned to you thanks.

**Comment by preetkaran20** [comment]
Hi @ShareACoke1 ,

Are you stuck at something regarding this issue? please let me know if you require some help.

thanks,
Karan

**Comment by ShareACoke1** [comment]
Hi, currently I am trying to solve this issue by redirecting the back button click as a refresh. As the URL doesn't change, this seemed like a solution. But it is not working yet.

**Comment by preetkaran20** [comment]
@ShareACoke1 Yeah, hiding some div's make it quite complex to achieve the exact back button state but i think trying to use the histories API can be beneficial. Please have a look at: https://medium.com/@george.norberg/history-api-getting-started-36bfc82ddefc

**Comment by ShareACoke1** [comment]
Hi @preetkaran20 , So far I have this: When I click on the Learn Security Button the URL changes to http://localhost:9090/learnVulnerabilities. When I click the Back button in the browser, the URL changes back and the Home button is clicked so everything is shown as default. What is your opinion about it?

**Comment by preetkaran20** [comment]
one question, does click on Learn Security button just changes the URL but doesn't call backend ? and what if i reenter the `http://localhost:9090/learnVulnerabilities` url and browser does it opens the vulnerability page ?

**Comment by ShareACoke1** [comment]
The button works as before, so it will show the vulnerabilities, however if you refresh or reenter http://localhost:9090/learnVulnerabilities it will throw an error. I have raised a PR.

**Comment by ShareACoke1** [comment]
Hi @preetkaran20 I would like to ask whether have you had time to look at it?

**Comment by preetkaran20** [comment]
Hi @ShareACoke1 ,

I had looked at the code, actually if we can do the same with opening the URL directly in browser then it would be great. I was thinking that we can parse the url, find the id's and click on the elements with those id's. this way we can achieve the full flow.

WDYT ?
Also i was planning to look at the router logics in frameworks so that we can do the same.

thanks,
Karan

**Comment by ShareACoke1** [comment]
Hi, I think this should be implemented in the Controller, however I'm not sure how to implement this yet.

**Comment by preetkaran20** [comment]
> Hi, I think this should be implemented in the Controller, however I'm not sure how to implement this yet.

one way which i think is using hash url which is internal routing but i think the same can be done without hashes, look at something like react router.

**Comment by ShareACoke1** [comment]
Hi @preetkaran20 I have looked into it, but I didn't find anything. So far I have managed to implement partial solution in the controller:
 ```
@RequestMapping(value = "/{[path:[^\\.]*}") 
public void redirect(HttpServletResponse response) throws IOException {
      response.sendRedirect("/");
}
```
This way the refresh redirects to the home page.

**Comment by preetkaran20** [comment]
Hi @ShareACoke1 ,

Please look at https://www.youtube.com/watch?v=mWeJnl9Ixxs , this way we can handle in UI instead of backend.

so logic is simple, have a Javascript which runs while loading the page and once page is loaded, it fetches the value after hash and then on the basis of that clicks some buttons/links

thanks,
Karan

**Comment by preetkaran20** [comment]
Closing this issue as this should be handled by VulnerableApp-Facade UI.
