### ISSUE TITLE
Docker image for VulnerableApp is heavy ~100MB

### ISSUE THREAD

**Issue by preetkaran20** [SasanLabs/VulnerableApp#202]
**Describe the bug**
Docker image is 107 MB which is quite big in comparison to other VulnerableApplication. This enhancement is to find what is causing this issue. Lets work on reducing this.

**Comment by preetkaran20** [comment]
Looking at this, it seems like docker base image is heavy and then springboot is adding to it but as we are updating entire jar which is not good because everytime someone pulls image they need to again pull all the same springboot dependencies.
How about adding springboot and then add the code to it so that springboot layer need not to be pulled everytime we release a new version.

**Comment by hemantgs** [comment]
> **Describe the bug**
> Docker image is 107 MB which is quite big in comparison to other VulnerableApplication. This enhancement is to find what is causing this issue. Lets work on reducing this.

One optimization I can think of right away is moving to `8-jre-alpine` from `8-jdk-alpine` , the image does not need jdk and all that overhead , so that is one option

> How about adding springboot and then add the code to it so that springboot layer need not to be pulled everytime we release a new version

Do you mean to say burning the .gradle or .m2 file into the base image and build and COPY the thin jar alone and not the fat jar ?

We can also think of 
https://github.com/GoogleContainerTools/jib?spm=a2c65.11461447.0.0.4c817ecchhAXns

**Comment by preetkaran20** [comment]
> > **Describe the bug**
> > Docker image is 107 MB which is quite big in comparison to other VulnerableApplication. This enhancement is to find what is causing this issue. Lets work on reducing this.
> 
> One optimization I can think of right away is moving to `8-jre-alpine` from `8-jdk-alpine` , the image does not need jdk and all that overhead , so that is one option

Great 👍 
> 
> > How about adding springboot and then add the code to it so that springboot layer need not to be pulled everytime we release a new version
> 
> Do you mean to say burning the .gradle or .m2 file into the base image and build and COPY the thin jar alone and not the fat jar ?
> 
Exactly
> We can also think of
> https://github.com/GoogleContainerTools/jib?spm=a2c65.11461447.0.0.4c817ecchhAXns
Sure will go through it.

**Comment by preetkaran20** [comment]
@hemantgs Jib is amazing, i read about it and also published one Jib image and it has reduced something close to 20MB

**Comment by hemantgs** [comment]
@preetkaran20 cool 😎 
Jib has spring boot gradle integration , if it fits the bill we can modify the build script to automatically push the image to docker-hub

**Comment by preetkaran20** [comment]
yes we already have that setup. we have written a github action for pushing images. I need to check how can jib use the credentials from Git Repo. Will do that setup. 
Our image it still 89MB is which is still big. What do you think shall we open this and wait for some time if we get some other idea ?

**Comment by preetkaran20** [comment]
One issue however we are using bash and Jib has not included `bash`. Need to work on it.

**Comment by preetkaran20** [comment]
Hi @hemantgs ,

I have integrated as per your suggestions like 1. Alpine Jre jar 2. Jib Integration and i think this is working fine.
https://github.com/SasanLabs/VulnerableApp/blob/master/.github/workflows/docker.yml
and some other changes.

Now the image size is 94 MB which is 15 MB lesser than the original. Now the left task is to just track if we can reduce further.

thanks,
Karan

**Comment by preetkaran20** [comment]
Multiple layers are added:
![image](https://user-images.githubusercontent.com/13570884/93015475-78b31f00-f5d7-11ea-959c-2971715da123.png)

Now we are looking if we can reduce the dependencies because we are not using everything so if we can remove all those extra dependencies.

**Comment by hemantgs** [comment]
@preetkaran20 A spring boot java image at ~100 MB is reasonably good I feel ,
Are other apps Java based ?

**Comment by preetkaran20** [comment]
> @preetkaran20 A spring boot java image at ~100 MB is reasonably good I feel ,
> Are other apps Java based ?

Agreed, 95 MB is great for SpringBoot application and i think there are less java based Applications but i always think Springboot has added so many dependencies which are not used by us and considering one time download for the users and then it will be layered Filesystem pull i think we can live with 95 MB.

WDYT ? shall we close this or shall we look at build.gradle to remove some of the wrongly added dependencies or any other areas of improvement?

**Comment by hemantgs** [comment]
@preetkaran20 
I had a look at the build.gradle and felt like it is already very minimal , just that spring-boot-starters bring in a bunch of other dependencies , If we started looking for things to exclude from the starters something might break.. 
IMHO we could close this , as like you said we could keep adding layers , for end user it might not be much of a hassle..We could close this

**Comment by preetkaran20** [comment]
closing it as per the discussion.
