### ISSUE TITLE
Evaluating Licence file on all the files

### ISSUE THREAD

**Issue by preetkaran20** [SasanLabs/VulnerableApp#210]
**Is your feature request related to a problem? Please describe.**
I have seen open source projects add the licence files about there classes/code so we can do the same with VulnerableApp to.
There are certainly some queries:
1. Why licence files are added ?
2. do we require to add on the files ?
3. Are there any complications and better if we can integrate with some plugin which will run and add the licence file. I know SpotlessApply can do that and it should not be very complicated.

**Describe the solution you'd like**
Use SpotlessApply. Requires above queries to be answered too.

**Describe alternatives you've considered**
Nothing

**Comment by hritikgupta** [comment]
would like to explore this, can i work on it?

**Comment by preetkaran20** [comment]
Hi @hritikgupta ,

Are you stuck at something regarding this issue? please let me know if you require some help.

thanks,
Karan

**Comment by hritikgupta** [comment]
Hi @preetkaran20, sorry for the late revert, I haven't been able to find time to work on it; would probably unassign myself so that someone else could take it up.

**Comment by preetkaran20** [comment]
> Hi @preetkaran20, sorry for the late revert, I haven't been able to find time to work on it; would probably unassign myself so that someone else could take it up.

No worries, thanks.

**Comment by preetkaran20** [comment]
Closing this issue as it is not needed.
