### ISSUE TITLE
Changing all the field level injections to constructor injection.

### ISSUE THREAD

**Issue by preetkaran20** [SasanLabs/VulnerableApp#211]
**Is your feature request related to a problem? Please describe.**
This is a tech debt. https://blog.marcnuri.com/field-injection-is-not-recommended/
If you look at all the vulnerabilities you will find that many are using field injection `@Autowired` on bean fields instead of Constructor which is not recommended because it loosed unit test ability etc. so this task is to move field to constructor injection.

**Comment by fengyuanyang** [comment]
I would like to take this issue as part of Hacktoberfest, could you assign to me

**Comment by preetkaran20** [comment]
Thanks @fengyuanyang for picking this changes.
