### ISSUE TITLE
UI Alignment is not proper for many levels.

### ISSUE THREAD

**Issue by preetkaran20** [SasanLabs/VulnerableApp#213]
**Is your feature request related to a problem? Please describe.**
As we are building UI from multiple sources hence for some of the levels UI is not aligned properly. This task is to align the UI better. 

Please download the docker images and check the alignment for the UI screen.
Eg. 
![image](https://user-images.githubusercontent.com/13570884/94943102-d8288e80-04f4-11eb-84c3-7e57dbe96a7f.png)

There are similar issues on other pages too.

**Comment by preetkaran20** [comment]
Please consider having a generic css so that developers writing new vulnerability need to not struggle with CSS.

**Comment by APalpattuwar7** [comment]
Can I work on this?

**Comment by ishitacodes** [comment]
I would like to work on this.

**Comment by preetkaran20** [comment]
Hi @APalpattuwar7 and @ishitacodes,

I think both of you can work on this. We can divide in a way like, one can work on the Vulnerability UI side and other can work on the framework UI (May be framework look and feel i.e. VulnerableApp.css)

Please let me know if this way works for you guys. In case both of you want to work on Vulnerability side then you guys can pick in a way like:
one can pick:
![image](https://user-images.githubusercontent.com/13570884/94980100-5f512300-0544-11eb-9703-42830fda4fa3.png)
and other can pick from the left vulnerabilities.

thanks,
Karan

**Comment by APalpattuwar7** [comment]
Let @ishitacodes do this work.

**Comment by preetkaran20** [comment]
Hi @ishitacodes ,

Are you looking into this issue ? and if so which part you are looking at, one part is alignment issue and another is a new UI structure for VulnerableApp.

thanks,
Karan

**Comment by ishitacodes** [comment]
Hey
I am looking into the alignment issue, do you have something specific in mind?

**Comment by preetkaran20** [comment]
Hi @ishitacodes ,

Great !!!. No nothing. please continue.

thanks,
Karan

**Comment by preetkaran20** [comment]
Hi @ishitacodes ,

Any updates on the task ? Are you stuck some where ? Please let me know.

thanks,
Karan

**Comment by rajeshranwa** [comment]
@preetkaran20 how about using a front-end framework for the whole UI?

**Comment by preetkaran20** [comment]
Hi @rajeshranwa ,

Thanks for the suggestion, few pointers:
1. Introducing new framework will tie the entire application with the framework and developers need to know about that framework. Might not be an issue if VulnerableApp is only one application but we are planning to make VulnerableApp as pool of applications. something like https://github.com/SasanLabs/VulnerableApp/issues/257 where each vulnerableApplication will provide a small html fragment and VulnerableApp-Ngnix will embed that html snippet into the entire page.
2. Also Frameworks will stop from writing vulnerable code like react/angular will not allow/make it hard to create a XSS vulnerability hence defeat our entire purpose.

However we can write some pros and cons to further evaluate this.

thanks,
Karan

**Comment by rajeshranwa** [comment]
makes sense.

**Comment by preetkaran20** [comment]
Hi, This issue should not happen in the new https://github.com/SasanLabs/VulnerableApp-facade UI. closing it. Will create a new one if the issue persists in VulnerableApp-Facade too.
