### ISSUE TITLE
Designing a Logo for VulnerableApp

### ISSUE THREAD

**Issue by preetkaran20** [SasanLabs/VulnerableApp#214]
**Is your feature request related to a problem? Please describe.**
One requirement we have is that VulnerableApp is not having any Logo. Suggestions are welcome. Please suggest some logo.

Designed logo can help VulnerableApp become unique. 
More information about VulnerableApp: https://sasanlabs.github.io/VulnerableApp/ and Readme.md file. Please go through documentation as that will help designing the logo better. 

thanks,
Karan

**Comment by preetkaran20** [comment]
Once logo is finalised then you can add the logo to the https://github.com/SasanLabs/VulnerableApp/blob/master/src/main/resources/static/index.html

**Comment by devabhishekpal** [comment]
I want to work on this issue
@preetkaran20

**Comment by preetkaran20** [comment]
Hi @devabhishekpal ,

Assigned you this feature.

thanks,
Karan

**Comment by devabhishekpal** [comment]
Thank you

**Comment by devabhishekpal** [comment]
I will be sending a few ideas for the logo by today evening.

**Comment by devabhishekpal** [comment]
What do you think about this?
![vulApp](https://user-images.githubusercontent.com/43001336/94995260-ce695e80-05ba-11eb-8dea-ee3cde0536af.png)

**Comment by preetkaran20** [comment]
@devabhishekpal  How would you describe it ? Looking at it, for me it looks like Vulnerabilities/issues are there if looked closely which is an amazing depiction. V -> is for vulnerableApp. correct me if i am wrong. When i open this images it is not showing me a proper image, is there any issue ?

@hemantgs  any comments on this?

**Comment by devabhishekpal** [comment]
Yes. The V was for VulnerableApp and since it is mainly for simulating vulnerabilities, but can be extended to search for them too I have made a magnification glass to symbolise searching of the same.

**Comment by devabhishekpal** [comment]
The pic is in Png transparent background so it isnt visible. Give me a minute I am uploading a white background version.😊

**Comment by devabhishekpal** [comment]
![vulApp](https://user-images.githubusercontent.com/43001336/94995530-9531ee00-05bc-11eb-9295-14632ca25bb3.png)

@preetkaran20 check this one

**Comment by hemantgs** [comment]
@devabhishekpal @preetkaran20 
I like the design 👍 shows what the app is about well ,
@devabhishekpal in case you have another version you're working on , we would love to have a look at that too 
Logos kind of stick to the app 🙂

**Comment by preetkaran20** [comment]
@hemantgs i was going to ask for the same.

**Comment by devabhishekpal** [comment]
Yes I had another idea with a V and the guy fawkes eyes

**Comment by devabhishekpal** [comment]
More like a combination of the VueJS V and the eyes

**Comment by devabhishekpal** [comment]
I had these two in mind too
![vulApp2](https://user-images.githubusercontent.com/43001336/94998273-442af580-05ce-11eb-9a7b-e07071fe0bc0.png)
![vulApp3](https://user-images.githubusercontent.com/43001336/94998274-455c2280-05ce-11eb-8fc8-7e1c276a7313.png)


@hemantgs @preetkaran20

**Comment by devabhishekpal** [comment]
The first is like a lock breaking indicating that the VulnerableApp was used to find a weakness.
The second is a V with a conical flask which shows the Payload Testing part of VulnerableApp

**Comment by preetkaran20** [comment]
Thanks @devabhishekpal , Lets do this, we ask ourselves some questions to better understand this:
Q. **What are the keywords which represents our project**
A. 1. Web Application 2. Deliberately Vulnerable Application 3. Security 4. Easy to add vulnerabilities (This is because we want ZAP or any other scanning tool developer to first write the vulnerability and then write scan rule in ZAP) 5. Bank of Vulnerabilities 6. Learn security by practise (Also know how not to write an application).

Q. **What is the target audience for our project**
A. Majority of audience is 1. Vulnerability Scanner tool developers (like ZAP developers etc.), 2. Students 3. In Future CTF organisers (Can be ignore for now) 

Now if we look at the very first design, we find that magnifying glass might represent something like scanner which might confuse too. @devabhishekpal @hemantgs please correct me if you think otherwise. 

Opened lock is a great representation of unsecure application because Closed one depicts secure however i think we need to think more on this.

So @devabhishekpal  can you please look at more logo's for VulnerableApplications (check https://owasp.org/www-project-vulnerable-web-applications-directory/) This project has list of such applications.  
I really liked the idea of looking at Vue.js logo and i think we can look at some more logo's and then finalise one (Lets do some more iterations for logo).

thanks,
Karan

**Comment by devabhishekpal** [comment]
Okayy sure @preetkaran20 😊

**Comment by devabhishekpal** [comment]
![vulApp4](https://user-images.githubusercontent.com/43001336/95009482-0f578680-0640-11eb-920f-4faebafca7e9.png)


I had this idea. And since it is under OWASP we could also maybe add that wasp inside the Magnifying glass. It would symbolize a Bug or rather a vulnerability in any application. What do you think? @preetkaran20

**Comment by devabhishekpal** [comment]
But the logo would be much smaller
I am sending a 32x32 size
Then you would get an idea of how it would look when applied somwhere.

**Comment by devabhishekpal** [comment]
![vulApp4_32](https://user-images.githubusercontent.com/43001336/95009558-8ee55580-0640-11eb-8a68-817769467a4f.png)


This is 32x32

**Comment by preetkaran20** [comment]
hmm, what does magnifying glass depicting ? It can depict something like a scan. what is your point of view.

@devabhishekpal @hemantgs

**Comment by devabhishekpal** [comment]
It is actually depicting searching of vulnerabilities. And then we can add the OWASP wasp in it maybe to show finding of the bugs. Provided it doesnt look cluttered on adding that

**Comment by preetkaran20** [comment]
that is actually the problem. When i look at it, it seems to me like a tool's logo which finds the vulnerabilities (Scans the vulnerabilities) where as this is opposite to that.

**Comment by preetkaran20** [comment]
Thinking out loud,

Can we do something like an Opened Lock eg. 
![image](https://user-images.githubusercontent.com/13570884/95010643-a3c5e700-0648-11eb-9869-220fada12738.png)

With the opening of lock having line from middle representing an A for application and Not sure how to fit V in this. Also How to represent the Developer of Scanners (Not sure). Ocean can represent other Deliberately Vulnerable Apps which lacks the Scanner as target audience.

@devabhishekpal Please add your thoughts on this.

**Comment by preetkaran20** [comment]
@devabhishekpal  was also thinking if we can have a shield with the VA design which you have mentioned above.
![image](https://user-images.githubusercontent.com/13570884/95011490-b2af9800-064e-11eb-9ae8-4c74c3addb02.png)
 May be VA is forming a broken line ?

**Comment by preetkaran20** [comment]
> ![vulApp4](https://user-images.githubusercontent.com/43001336/95009482-0f578680-0640-11eb-920f-4faebafca7e9.png)
> 
> I had this idea. And since it is under OWASP we could also maybe add that wasp inside the Magnifying glass. It would symbolize a Bug or rather a vulnerability in any application. What do you think? @preetkaran20

While looking at VA part it looks amazing. @hemantgs any comments

**Comment by devabhishekpal** [comment]
Yeah I can do the shield with breaking and VA @preetkaran20

**Comment by preetkaran20** [comment]
thanks @devabhishekpal . we can do pros and cons for both the logos.

thanks,
Karan

**Comment by devabhishekpal** [comment]
I am sending the new one by evening

**Comment by devabhishekpal** [comment]
![vulApp5_32](https://user-images.githubusercontent.com/43001336/95018598-6aa86980-067e-11eb-8945-bb2aa5a8422e.png)






![vulApp5](https://user-images.githubusercontent.com/43001336/95018596-69773c80-067e-11eb-9dba-f5f39a0f427d.png)


This is what I had in mind. The VA is inside the shield giving the effect of a crack in it.

**Comment by preetkaran20** [comment]
Hi @devabhishekpal , 

To me it looks good. May be we can change the background of shield to white and border as black. Similar to the image I sent you. Also I think the mirror image of the shield image I have added above can make a V with A. Dimension of A can be smaller than the V to make crack look better

@hemantgs  please share your thoughts

**Comment by preetkaran20** [comment]
Thinking again.

I think this looks good just the start of V and End of A can be smooth and doesn't require special curve. i.e. 
![image](https://user-images.githubusercontent.com/13570884/95019285-1901de00-0682-11eb-8c22-b70d93f0c8e4.png)

**Comment by preetkaran20** [comment]
One candidate could be 
![image](https://user-images.githubusercontent.com/13570884/95019379-a8a78c80-0682-11eb-8c13-e561a9e0a85a.png) too where instead of this sign there can be our VA sign.

**Comment by preetkaran20** [comment]
@devabhishekpal also check if we reduce the line size as we keep going to A from V sign.
Something similar to the above flash sign. How does it looks ?

**Comment by preetkaran20** [comment]
Also how about changing little bit more something like:
![image](https://user-images.githubusercontent.com/13570884/95019588-d3461500-0683-11eb-89f4-1341ea0ea4e7.png)

**Comment by preetkaran20** [comment]
Hi @devabhishekpal ,

I think https://github.com/SasanLabs/VulnerableApp/issues/214#issuecomment-703269698 one change will make the logo final. Please proceed with this change and then let's choose one. 

thanks,
Karan

**Comment by devabhishekpal** [comment]
Okaayyy

**Comment by devabhishekpal** [comment]
![vulApp5](https://user-images.githubusercontent.com/43001336/95020825-1fe11e80-068b-11eb-9057-ec4fdde3b36c.png)


The change isnt looking as good
But I have thought of some changes. I am sending those by morning. I was thinking about making the one from [this comment](https://github.com/SasanLabs/VulnerableApp/issues/214#issuecomment-703271520) and adding the VA in the center. Or taper off the edges of V and A to make them pointy at the point they are touching the shield

**Comment by preetkaran20** [comment]
Yeah you are right. Let's see.

thanks,
Karan

**Comment by preetkaran20** [comment]
Hi @devabhishekpal , 
Did you got time to look into this? 

Thanks, 
Karan

**Comment by devabhishekpal** [comment]
Yes, sorry I had a hectic week with assignment submissions😅 will positively send the new one by today
preetkaran20

**Comment by devabhishekpal** [comment]
![va](https://user-images.githubusercontent.com/43001336/96009491-558dc080-0e5e-11eb-846d-39f7b3f72ee3.png)
![va1](https://user-images.githubusercontent.com/43001336/96009494-56beed80-0e5e-11eb-8f53-fadda8d47793.png)

What do you think about these? @preetkaran20

**Comment by preetkaran20** [comment]
one question, can we have a smaller VA ? just to compare. example https://github.com/SasanLabs/VulnerableApp/issues/214#issuecomment-703271520

**Comment by preetkaran20** [comment]
if possible can we have little less width V edges, it looks little big.

**Comment by devabhishekpal** [comment]
Yes

**Comment by devabhishekpal** [comment]
![va](https://user-images.githubusercontent.com/43001336/96018412-da7dd780-0e68-11eb-9f7e-45eace818592.png)
![va1](https://user-images.githubusercontent.com/43001336/96018416-dbaf0480-0e68-11eb-92b0-ea13d624c85b.png)


These are the new modifications.
On the first one I changed the V a bit to make it go from wide at the edge to thinner at the middle so that it looks more like a crack.
The second one is what you requested i.e. I reduced the width of the V @preetkaran20

**Comment by preetkaran20** [comment]
@hemantgs  what do you think ? For me 2nd one looks amazing.

**Comment by hemantgs** [comment]
@preetkaran20 Sorry , I missed the previous discussions ..
So I dig both the designs .. excellent work from @devabhishekpal 
We can pick the second @preetkaran20 Looks good

**Comment by preetkaran20** [comment]
thanks @hemantgs.

@devabhishekpal  can you please give 3 different resolution logo's (check some site like github for standard way to provide the logo).
Then we can add these logo's to 
1. index.html page in VulnerableApplication
2. Documentation website(https://sasanlabs.github.io/VulnerableApp/) and Readme file.
3. adding the logo to Owasp Website (https://owasp.org/www-project-vulnerableapp/)

I also think that we might color the logo too. what you guys think ? 

thanks,
Karan

**Comment by devabhishekpal** [comment]
A colour will pop out more. It is a great idea. What colour scheme do you have in mind? @preetkaran20 @hemantgs ? I was thinking something in the yellowish orange range to give that warm yet kind of a warning type of vibe?

**Comment by preetkaran20** [comment]
@devabhishekpal yeah makes sense. Actually only issue is combination with VulnerableApp's existing design. Lets have Black and white logo as well as yellowish orange logo both.

**Comment by devabhishekpal** [comment]
Okayy @preetkaran20 then I am adding 2sets of 3resolutions. One b/w and one coloured.

**Comment by devabhishekpal** [comment]
![iconColoured](https://user-images.githubusercontent.com/43001336/96336097-dfc26880-109a-11eb-9503-01eba58eacef.png)


This is the coloured version. What do you think? @hemantgs @preetkaran20

**Comment by preetkaran20** [comment]
wow !!!

**Comment by preetkaran20** [comment]
This has outline color little different correct ? It looks amazing , Too good @devabhishekpal

**Comment by devabhishekpal** [comment]
> This has outline color little different correct ? It looks amazing , Too good @devabhishekpal 

Yes the outline has a different colour. Yellow and orange.

**Comment by preetkaran20** [comment]
I think we are good to have a PR with logo's and then have them at multiple other places as mentioned https://github.com/SasanLabs/VulnerableApp/issues/214#issuecomment-708968874

**Comment by preetkaran20** [comment]
Hi @devabhishekpal ,

Please let me know if you are interested in integrating logo's at multiple places like:

1. index.html page in VulnerableApplication
2. Documentation website(https://sasanlabs.github.io/VulnerableApp/) and Readme file.
3. adding the logo to Owasp Website (https://owasp.org/www-project-vulnerableapp/)

thanks,
Karan

**Comment by devabhishekpal** [comment]
Yes @preetkaran20

**Comment by preetkaran20** [comment]
Hi @devabhishekpal ,

I have updated Owasp Website and Docker readme (As they require more access permissions). Please go through 
1. index.html page in VulnerableApplication
2. Documentation website(https://sasanlabs.github.io/VulnerableApp/) and Readme file.

thanks,
Karan

**Comment by devabhishekpal** [comment]
Okayyy

**Comment by preetkaran20** [comment]
https://github.com/OWASP/owasp-swag/pull/44

**Comment by preetkaran20** [comment]
Hi @devabhishekpal ,

I have done the changes at both the places. Thanks a lot for designing the Logo and helping us with such an amazing logo design.

thanks,
Karan

**Comment by devabhishekpal** [comment]
Hey no problem😊 It was really fun and helped me gain experience too and thanks a lot for all the help on your end too.
