### ISSUE TITLE
Some Vulnerability are not having User Interface

### ISSUE THREAD

**Issue by preetkaran20** [SasanLabs/VulnerableApp#219]
**Is your feature request related to a problem? Please describe.**
As there are some Vulnerabilities which are not having user interface so we are showing some response using "sasan.html" file. 

**Describe the solution you'd like**
So in this feature, a error page with better details and proper naming is needed.
Content of the HTML page should be depicting the reason and may be little nicer UI.

![image](https://user-images.githubusercontent.com/13570884/94988729-022d8f80-058d-11eb-94a3-5516fa4976af.png)
This is the current page and this is looks quite odd.

**Comment by Nimanita** [comment]
@preetkaran20  we have to design good html pages for showing above  error? if yes,than please assign this issue to me.

**Comment by preetkaran20** [comment]
Yes we have to design some good error page. but we cannot change the entire page structure because of the basic design which we are having. I suggest you to go through https://sasanlabs.github.io/VulnerableApp/DesignDocumentation.html documentation for more information.

For entire structure change we have created another issue https://github.com/SasanLabs/VulnerableApp/issues/213.

thanks,
Karan

**Comment by Nimanita** [comment]
@preetkaran20 Yes I will love to work on it.I will add some css style to make it better and I will keep in mind to not change basic layout

**Comment by preetkaran20** [comment]
Hi @Nimanita ,

Assigned this task to you.

thanks,
Karan

**Comment by preetkaran20** [comment]
Thanks @Nimanita for completing this issue. Hence Closing this task.
