### ISSUE TITLE
Creating GIFs on how to use the project and how to add new vulnerabilities

### ISSUE THREAD

**Issue by preetkaran20** [SasanLabs/VulnerableApp#240]
This task is to create gifs to describe the project and its usage.

**Comment by preetkaran20** [comment]
@hemantgs  I have created a GIF, does this works ?
![Owasp VulnerableApp(2)](https://user-images.githubusercontent.com/13570884/97084522-53351e80-1635-11eb-91c2-38afa8c04f0a.gif)


thanks,
Karan

**Comment by hemantgs** [comment]
@preetkaran20 looks good.. I think we can roll with this 👍

**Comment by preetkaran20** [comment]
How to add a new vulnerability i will cover in a video series.
