### ISSUE TITLE
Links for learning in the app opens in same page

### ISSUE THREAD

**Issue by preetkaran20** [SasanLabs/VulnerableApp#249]
**Describe the bug**
Say on learn jwt page when I click on a link it opens in same window causing users to click by holding control key. Also for single page application it looks odd

Simple solution is putting blank as target for links or we need to have a way to tell browser open in new tab

**Comment by Edu93Jer** [comment]
Hi, @preetkaran20  I am a newbie to this project and would like to contribute it; do you think you can put me in the right direction, please?

**Comment by preetkaran20** [comment]
Hi @Edu93Jer ,

Yeah Sure. you can go through [Overview Video](https://www.youtube.com/watch?v=AjL4B-WwrrA&ab_channel=OwaspVulnerableApp) for information about the project.

Each vulnerability has some description about the vulnerability and that description contains some external links which explains the vulnerability but as those links open in the same window as the vulnerableApp hence users need to press the control key to open those links in new tab so this bug is to fix this issue.

Now talking about how these descriptions are generated, please have a look at: https://sasanlabs.github.io/VulnerableApp/DesignDocumentation.html

thanks,
Karan

**Comment by Edu93Jer** [comment]
@preetkaran20 sorry to disturb you I was busy, but now I will be working on the issue, looks kind of easy to solve, but another question for me to understand better, the HTML tags are the one that are located at [https://github.com/SasanLabs/VulnerableApp/tree/master/src/main/resources/i18n](url) those 2 files right? 

Cheers,
Edu

**Comment by preetkaran20** [comment]
Hi @Edu93Jer , 
Yes most of them are there in those i18n files, however one or 2 can be there at html pages. 

Thanks, 
Karan

**Comment by preetkaran20** [comment]
closing this as @Edu93Jer has fixed this.

thanks
