### ISSUE TITLE
Adding a way to include some indicator for FalsePositives

### ISSUE THREAD

**Issue by preetkaran20** [SasanLabs/VulnerableApp#258]
**Is your feature request related to a problem? Please describe.**
Currently we can add the vulnerabilities in the VulnerableApp but there is no way to have some false positives "Secure" implementations such that we can better judge the scanners.

**Additional context**
we have a level which is called "secure" but we might need something like "secure1" , "secure2" etc. so that those can be secure implementations and "/scanner" endpoint will return those and then in Owasp ZAP evaluation script we can include it.

Owasp ZAP Integration with VulnerableApp: https://github.com/zapbot/zap-mgmt-scripts/tree/master/vulnerableApp

**Comment by nowakkamil** [comment]
As discussed with @preetkaran20, @marcin-wrotecki and I are going to work on this issue.

**Comment by nowakkamil** [comment]
_Notes from the recent discussion with @preetkaran20 and @marcin-wrotecki:_

First of all, the level should be used to represent tier only. We ought to add another field to distinguish whether it is secure or not.

### Approaches considered:

1. Backend `/allEndPointJson` won't return any secure levels, it will respond with insecure ones only. However, `/scanner` will return secure vulnerabilities as well.
2. Strive for consistency by returning both types (secure and unsecure) by  `/allEndPointJson` and `/scanner`, and have in UI the secure level visually marked.

**The second approach was chosen, and this is the acceptance criteria for this ticket.**

### Implementation proposals:

1. Introduce brand new annotation, for instance, `@Secure`.
Drawback: There is no way to remind the developer to add `@Secure` - he can forget to add one, and we cannot enforce it.
2. Add optional parameter to existing `VulnerableAppRequestMapping` annotation.
3. Infer secure/insecure by the presence of @AttackVector.
Downside: Currently, `@AttackVector` is present on both types - secure/insecure.

**The second approach was chosen.**

### Additional notes:

`Type` name might be adjusted later on to reflect its purpose; to signify whether vulnerability implementation is secure or unsecure.
If possible, get rid of the secure level in `XSSInImgTagAttribute` - replace it with the new level number.

**Comment by preetkaran20** [comment]
As there is one more step left which is VulnerableApp-Nginx update hence reopening the task.
