### ISSUE TITLE
Not able to import into eclipse or any other ide

### ISSUE THREAD

**Issue by effortlessdevsec** [SasanLabs/VulnerableApp#269]
i m not able to import this code in eclipse.

The import org.springframework cannot be resolved

**Comment by preetkaran20** [comment]
Hi @effortlessdevsec ,

Are you using eclipse gradle to import it ?

**Comment by effortlessdevsec** [comment]
yes, 
![image](https://user-images.githubusercontent.com/30777722/105020312-26927680-5a6d-11eb-9141-be1862ef84c7.png)

**Comment by effortlessdevsec** [comment]
I missing gradlew build but after it on run it showing again error , please have a look

**Comment by preetkaran20** [comment]
I just now tried importing to eclipse it is working. can you please right click on build.gradle > gradle -> refresh project and send me the output.

**Comment by preetkaran20** [comment]
@effortlessdevsec in case you are still facing issues please let me know, we can have a call and fix this.

thanks,
Karan

**Comment by effortlessdevsec** [comment]
got it , there is a issue in gradle-wrapper (distribution url) . after whole day spent  on finding solution change it to https\://services.gradle.org/distributions/gradle-6.7.1-bin.zip
now working

**Comment by preetkaran20** [comment]
@effortlessdevsec oh ok. If you still face any issues or you are looking for any enhancement feel free to raise a issue. 
Thanks, 
Karan
