### ISSUE TITLE
PersistentXSS LEVEL_4 can not take effect

### ISSUE THREAD

**Issue by GitHubNull** [SasanLabs/VulnerableApp#308]
**Describe the bug**
I think PersistentXSS LEVEL_4 can not take effect, beceause the code: https://github.com/SasanLabs/VulnerableApp/blob/621499b753c68f18bd8c37e90795dae9e595b47e/src/main/java/org/sasanlabs/service/vulnerability/xss/persistent/PersistentXSSInHTMLTagVulnerability.java#L163.
It was not bug?  If it is not bug, how to take it effect.

**Comment by preetkaran20** [comment]
PR: https://github.com/SasanLabs/VulnerableApp/pull/309

**Comment by preetkaran20** [comment]
Closing this issue as it is fixed now in the unreleased version.
@GitHubNull  Thanks for finding this out. Please raise the issue if you find similar issues in future.
thanks,
Karan
