### ISSUE TITLE
Issues with Hint Message in Error Based SQL Injection and union Based SQL Injections

### ISSUE THREAD

**Issue by preetkaran20** [SasanLabs/VulnerableApp#310]
**Describe the bug**
Error-based SQL Injection and Union-based SQL Injection has hints which have messages without space between 2 words in multiple levels. 

![image](https://user-images.githubusercontent.com/13570884/134773900-e5cde155-7cb6-4b4c-bd46-e9a46f234d83.png)

**How to fix**
Correct the string in messages files: https://github.com/SasanLabs/VulnerableApp/tree/master/src/main/resources/i18n.

**Comment by priyanka010392** [comment]
Hello @preetkaran20, could you please assign it to me? I would like to work on it during Hacktober fest

**Comment by preetkaran20** [comment]
Closing this issue as this is fixed by the #326
