### ISSUE TITLE
Fixing issues in PersistentXSSInHTMLTagVulnerability  

### ISSUE THREAD

**Issue by preetkaran20** [SasanLabs/VulnerableApp#314]
**Is your feature request related to a problem? Please describe.**
PersistentXSSInHTMLTagVulnerability has few issues:
1. The method names contains the Vulnerability level and they are not matching eg: 
![image](https://user-images.githubusercontent.com/13570884/134774804-cacb990f-421c-493b-a9a9-706077780f25.png)
2. Secure level also contains the attack vector annotation, last level i.e. https://github.com/SasanLabs/VulnerableApp/blob/master/src/main/java/org/sasanlabs/service/vulnerability/xss/persistent/PersistentXSSInHTMLTagVulnerability.java#L238-L256 contains the AttackVector annotation which it should not. So we need to fix that.
3.  Need to validate that the levels marked as unsecured are unsecured and secure and secured.

**Describe the solution you'd like**
1. Correct the method names in https://github.com/SasanLabs/VulnerableApp/blob/master/src/main/java/org/sasanlabs/service/vulnerability/xss/persistent/PersistentXSSInHTMLTagVulnerability.java
2. Removed Attack vector annotation and the references like description keys
3. Validate all the levels are rightly marked secured and unsecured.

**Comment by 1411dolly0** [comment]
Hi

I would like to work on it.

**Comment by 1411dolly0** [comment]
Hi

I have a query. How to validate levels are secured or unsecured.

**Comment by preetkaran20** [comment]
Hi @1411dolly0,

Yes, that is challenging but generally, we can try different payloads, look at the code to see if we have done something wrong to introduce the vulnerability, follow the guidelines in Owasp. However, try to find the payloads to break it is best way.

**Comment by preetkaran20** [comment]
Hi @1411dolly0 ,

Easier way is to just build a docker image by running following command:
```
./gradlew jib 
```
and then download https://github.com/SasanLabs/VulnerableApp-facade/blob/main/docker-compose.yml and run docker-compose up, then you can navigate to localhost will be give you a UI.

thanks,
Karan
