### ISSUE TITLE
Vulnerability Type And Vulnerability Subtype enhancements

### ISSUE THREAD

**Issue by preetkaran20** [SasanLabs/VulnerableApp#325]
**Is your feature request related to a problem? Please describe.**
Currently, we are having 2 Vulnerability classifications:
1. https://github.com/SasanLabs/VulnerableApp/blob/master/src/main/java/org/sasanlabs/vulnerability/types/VulnerabilityType.java
2. https://github.com/SasanLabs/VulnerableApp/blob/master/src/main/java/org/sasanlabs/vulnerability/types/VulnerabilitySubType.java
and both are redundant, also there is no CWE and WASC mapping of these types causing issues when mapping between various systems like DAST/SAST report comparison (For more information: https://github.com/SasanLabs/VulnerableApp/blob/master/scanner/sast/expectedIssues.csv).

**Changes we are looking for/Definition of Done**
These two were created because of some historical reasons and my lack of understanding, now things are more clearer so we are looking for the following changes:

1. Delete the VulnerabilityType class
2. Rename VulnerabilitySubType class to VulnerabilityType
3. Remove VulnerabilityType from https://github.com/SasanLabs/VulnerableApp/blob/master/src/main/java/org/sasanlabs/internal/utility/annotations/VulnerableAppRestController.java annotation
4. Remove [Null_Byte](https://github.com/SasanLabs/VulnerableApp/blob/master/src/main/java/org/sasanlabs/vulnerability/types/VulnerabilitySubType.java#L41) and all its references
5. Change references to older VulnerabilityType to newer VulnerabilityType (Which was VulnerabilitySubType) at: https://github.com/SasanLabs/VulnerableApp/blob/master/src/main/java/org/sasanlabs/service/impl/EndPointsInformationProvider.java
6. Add CWE and WASC numbers to  https://github.com/SasanLabs/VulnerableApp/blob/master/src/main/java/org/sasanlabs/vulnerability/types/VulnerabilitySubType.java for each VulnerabilityType.
7. Update the documentation: https://github.com/SasanLabs/VulnerableApp/tree/master/docs if there are any references to VulnerableAppRestController annotation.

**Comment by 1411dolly0** [comment]
I like to work on it.

**Comment by preetkaran20** [comment]
Sure, I have assigned it to you. 

Thanks, 
Karan

**Comment by 1411dolly0** [comment]
After removing :- Remove VulnerabilityType from https://github.com/SasanLabs/VulnerableApp/blob/master/src/main/java/org/sasanlabs/internal/utility/annotations/VulnerableAppRestController.java annotation

It is being used in EndPointsInformationProvider class. Line number 69. 

<img width="1792" alt="Screenshot 2021-09-30 at 12 33 57 PM" src="https://user-images.githubusercontent.com/73784751/135403811-3be277a6-acdc-496c-ad33-f415944abc1d.png">


Please let me know if its reference need to be removed also.

**Comment by preetkaran20** [comment]
Thanks for pointing it out. I think we can remove this method in allEndPointResponseBean

**Comment by 1411dolly0** [comment]
Hi

For:- Add CWE and WASC numbers to https://github.com/SasanLabs/VulnerableApp/blob/master/src/main/java/org/sasanlabs/vulnerability/types/VulnerabilitySubType.java for each VulnerabilityType.

I was able to find CWE in https://github.com/SasanLabs/VulnerableApp/blob/master/src/main/java/org/sasanlabs/vulnerability/types/VulnerabilitySubType.java for each VulnerabilityType.

Can you please help me with WASC associated with each?

**Comment by preetkaran20** [comment]
Hi @1411dolly0 ,

Please check if http://projects.webappsec.org/w/page/13246975/Threat%20Classification%20Taxonomy%20Cross%20Reference%20View or http://projects.webappsec.org/w/page/13246978/Threat%20Classification works ? 

thanks,
Karan

**Comment by preetkaran20** [comment]
Hi @1411dolly0 ,

Are you able to proceed on this task? Please let me know if you face any issues.

thanks,
Karan

**Comment by 1411dolly0** [comment]
Hi

I have raised PR. Please review.

**Comment by preetkaran20** [comment]
@1411dolly0  thank you for the changes. If possible, please mention your name as we will add it to release notes.

thanks,
Karan

**Comment by 1411dolly0** [comment]
Hi
 
Myself Dolly, Thank you. 😇
