### ISSUE TITLE
Removing deprecated fields from VulnerableAppRequestMapping annotation and ScannerResponseBean

### ISSUE THREAD

**Issue by preetkaran20** [SasanLabs/VulnerableApp#335]
**Is your feature request related to a problem? Please describe.**
[VulnerableAppRequestMapping](https://github.com/SasanLabs/VulnerableApp/blob/master/src/main/java/org/sasanlabs/internal/utility/annotations/VulnerableAppRequestMapping.java) annotation and [ScannerResponseBean](https://github.com/SasanLabs/VulnerableApp/blob/master/src/main/java/org/sasanlabs/beans/ScannerResponseBean.java) contains few deprecated fields. 

**Describe the solution you'd like**
Earlier due to lack of my understanding, I have added few parameters for scanners but later I realized that these parameters are not helpful.

**Definition of Done**
Please remove the deprecated fields and their references in both these files.

**Comment by Monoradioactivo** [comment]
I'm working on this!
