### ISSUE TITLE
Fixing Sonar Issues

### ISSUE THREAD

**Issue by preetkaran20** [SasanLabs/VulnerableApp#347]
**Is your feature request related to a problem? Please describe.**
Currently the project has many sonar issues, we know that fixing sonar issues in vulnerable application is complex but some of the code smells can be fixed. This task is to remove those code smells.

**Comment by preetkaran20** [comment]
This task can be done in various steps, like one class at a time.

**Comment by SangameshItagi** [comment]
Hey @preetkaran20 Can i pick this issue? I will fix sonar issues in couple of class

**Comment by hks1** [comment]
Hey @preetkaran20 I see a few sonar issues (critical code smells). Can I pick some of them?

**Comment by preetkaran20** [comment]
Hi @hks1 ,

Yeah sure. I have assigned the issue to you.

thanks,
Karan
