### ISSUE TITLE
Http3XXStatusCodeBased injection vulnerability doesn't work with VulnerableApp Facade

### ISSUE THREAD

**Issue by preetkaran20** [SasanLabs/VulnerableApp#359]
**Describe the bug**
<img width="1536" alt="image" src="https://user-images.githubusercontent.com/13570884/157090790-8a8dc2bd-8655-4a76-9f7b-e83a1295f796.png">

**To Reproduce**
Go to Http3XXStatusCodeBasedInjection Vulnerability and click on click here link as shown in the above image. it will route to a new webpage but that webpage will not open and will fail.

**Expected behavior**
The URL should be able to open some webpage in VulnerableApp (either we should create a webpage or we should show some logo page). The code is present at: https://github.com/SasanLabs/VulnerableApp/blob/master/src/main/java/org/sasanlabs/service/vulnerability/openRedirect/Http3xxStatusCodeBasedInjection.java

**Comment by Azhen917** [comment]
Hello I am new to open source contributions. I tried to reproduce the issue but it seems to have routed back to the starting page after clicking on the URL.
![image](https://user-images.githubusercontent.com/68435405/157595906-57f2b825-f5c7-41be-9285-b65d093b47c9.png)

**Comment by preetkaran20** [comment]
Hi @Azhen917,

Thanks for looking at it, actually issue is with the newer user interface. if you try newer interface you will find the issue. the goal is to fix the issue for both the UI.
2nd point in the [section](https://github.com/SasanLabs/VulnerableApp#building-the-project)

thanks,
Karan

**Comment by preetkaran20** [comment]
I will also update the readme and make the 2nd option as 1st so that more people become aware about the official UI.

**Comment by ehizman** [comment]
I will like to work on this.

**Comment by preetkaran20** [comment]
Sure, assigned to you.

**Comment by ehizman** [comment]
Hello @preetkaran20 . I tried to reproduce the issue. I added this docker-compose.yml file

```yml
version: "2.2"
services:
  VulnerableApp-base:
    image: sasanlabs/owasp-vulnerableapp:unreleased
    ports:
      - "9090:9090"
```
I was able to connect on `http://localhost:9090/VulnerableApp/` but whenever I click on the "Click here" link. It redirects to the homepage

**Comment by preetkaran20** [comment]
Hi @ehizman ,
Sorry for the late reply. 

You will find this issue if you start looking at the newer UI. i.e use following docker compose file: https://github.com/SasanLabs/VulnerableApp-facade/blob/main/docker-compose.yml and hit `http://localhost`

**Comment by ehizman** [comment]
Hello @preetkaran20 .
I build the image and then when I run `sudo docker-compose up`. I get the following error:
```bash
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services: 'VulnerableApp-base'
```

**Comment by preetkaran20** [comment]
Hi @ehizman , 

Which version of docker-compose are you using?
If older version, please try newer.

**Comment by ehizman** [comment]
Hello @preetkaran20. I am sorry, I was able to get it started using the `docker compose up` command and not `docker-compose up`

**Comment by ehizman** [comment]
Hi @preetkaran20. Its like you forgot close this issue

**Comment by preetkaran20** [comment]
@ehizman closed it.
