### ISSUE TITLE
Add unit tests for Blind Sql Injection Vulnerability

### ISSUE THREAD

**Issue by preetkaran20** [SasanLabs/VulnerableApp#392]
**Is your feature request related to a problem? Please describe.**
We are looking at increasing the Test coverage for the project for its stability so this task is to add junit tests for https://github.com/SasanLabs/VulnerableApp/blob/master/src/main/java/org/sasanlabs/service/vulnerability/sqlInjection/BlindSQLInjectionVulnerability.java

**Comment by preetkaran20** [comment]
Parent issue: https://github.com/SasanLabs/VulnerableApp/issues/212

**Comment by imertetsu** [comment]
Hello @preetkaran20 I see this issue is still open so I'd like to work on it. :)

**Comment by preetkaran20** [comment]
Hi @imertetsu , 

Sure, I have assigned you the issue.
