### ISSUE TITLE
Add unit tests for SSRF vulnerability

### ISSUE THREAD

**Issue by preetkaran20** [SasanLabs/VulnerableApp#397]
**Is your feature request related to a problem? Please describe.**
We are looking at increasing the Test coverage for the project for its stability so this task is to add junit tests for https://github.com/SasanLabs/VulnerableApp/tree/master/src/main/java/org/sasanlabs/service/vulnerability/ssrf

**Comment by rai-sandeep** [comment]
Hello! I would like to work on this issue. Can I go ahead?

**Comment by preetkaran20** [comment]
Hi @rai-sandeep , 

Yes, sure.

Thanks, 
Karan

**Comment by rai-sandeep** [comment]
@preetkaran20 PR for review: https://github.com/SasanLabs/VulnerableApp/pull/429

**Comment by rai-sandeep** [comment]
@preetkaran20 Please review my PR https://github.com/SasanLabs/VulnerableApp/pull/429
