### ISSUE TITLE
Add unit tests for JWT Vulnerability

### ISSUE THREAD

**Issue by preetkaran20** [SasanLabs/VulnerableApp#398]
**Is your feature request related to a problem? Please describe.**
We are looking at increasing the Test coverage for the project for its stability so this task is to add junit tests for https://github.com/SasanLabs/VulnerableApp/tree/master/src/main/java/org/sasanlabs/service/vulnerability/jwt

**Comment by preetkaran20** [comment]
Parent issue: #212

**Comment by ehizman** [comment]
Working on this Karan.
Yes, I am back!

**Comment by preetkaran20** [comment]
@kjosh has merged the Unit tests for JWT. Hence closing the ticket.
