### ISSUE TITLE
Possibility to add the Italian translation

### ISSUE THREAD

**Issue by TheZal** [SasanLabs/VulnerableApp#414]
Hi, like #371 I would like to indtroduce the Italian translation.
If you will assign this issue to me I would like to contribute as soon as possible adding a file "messages_it_IT.properties" based on the messages_en_US.properties file.

**Comment by preetkaran20** [comment]
Hi @TheZal ,

Sure, just one thing, we need to figure out the user's locale as well somehow and pass it to the backend, can you please explore that too if possible?

thanks,
Karan

**Comment by TheZal** [comment]
I'll try in future in another issue!

**Comment by preetkaran20** [comment]
Closing the ticket. Thank you
