### ISSUE TITLE
Add Spanish translation to resources

### ISSUE THREAD

**Issue by dafarias** [SasanLabs/VulnerableApp#418]
Hello!

Based on #371, I'd like to work in the feature or enhancement to add the Spanish translation based on the **messages_en_US.properties** file.

I'm also new to making contributions into open source, so I'm open to any suggestions.

Thank you.

**Comment by preetkaran20** [comment]
Hi @dafarias,

Sure, please go ahead with the implementation. Along with this change, can you also try for https://github.com/SasanLabs/VulnerableApp/issues/416 ? This task is to use the Request locale header and pick the right locale.

please let me know if you have any questions.

thanks,
Karan

**Comment by preetkaran20** [comment]
@dafarias  perfect !!! sure.

**Comment by preetkaran20** [comment]
Hi @dafarias ,

I have included the support of Accept Language header so when you now try to launch the application after spanish changes, it should launch application in spanish.

thanks,
Karan

**Comment by preetkaran20** [comment]
Thanks you !!!
