### ISSUE TITLE
Fix SSRFVulnerabilityTest to mock the network calls.

### ISSUE THREAD

**Issue by preetkaran20** [SasanLabs/VulnerableApp#445]
**Is your feature request related to a problem? Please describe.**
SSRF vulnerability test is doing the network calls while running tests and causing failures. Reported issue: https://github.com/SasanLabs/VulnerableApp/issues/443

**Describe the solution you'd like**
We would like to mock the network call such that these failures can be handled.

@bperry-mf @000panther

**Comment by Vijay-948** [comment]
can you assign me?

**Comment by tkomlodi** [comment]
@Vijay-948, I've already have a fix if you haven't gotten started yet. If you prefer, I can also just send you what I have. 

@preetkaran20, I should have probably signaled before getting started. In either case, I can contribute it or just throw it away.

Thanks

**Comment by Vijay-948** [comment]
"No problem at all. I appreciate your willingness to contribute. Please go ahead.

**Comment by preetkaran20** [comment]
Thanks a lot for the PR @tkomlodi. I have merged the changes.

**Comment by tkomlodi** [comment]
@preetkaran20, thanks for accepting the fix! I've been using OWASP tools for many years so I'm happy I can give back in a very modest way. I'll see if I can pick up some more issues.
Thanks

**Comment by preetkaran20** [comment]
@tkomlodi thanks and sure, please go ahead.
