### ISSUE TITLE
Jar file was not released as part of the assets in the latest release

### ISSUE THREAD

**Issue by trabetti-hcl** [SasanLabs/VulnerableApp#468]
The new release does not contain a jar file as part of the assets. Instructions indicate one of the methods to run the app is using the jar.
Would it be possible to add the jar file to the assets, or provide an alternative for running the app without using docker-compose.

Thank you!

**Comment by preetkaran20** [comment]
@trabetti-hcl Thanks for mentioning it. We have released the newer version.

**Comment by trabetti-hcl** [comment]
Thank you for the quick response!
